apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api-{{VERSION}}
  labels:
    app: events-api
    ver: {{VERSION}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-api
      ver: {{VERSION}}
  template:
    metadata:
      labels:
        app: events-api
        ver: {{VERSION}}
    spec:
      containers:
      - name: events-api
        image: {{IMAGE}}
        ports:
        - containerPort: 8082
        env:
        - name: DBHOST
          value: "database-server-mariadb.default"
        - name: DBUSER
          value: "root"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: database-server-mariadb
              key: mariadb-root-password
        - name: DBDATABASE
          value: "events_db"
 
